"""Split-mould negative generator — the printable deliverable.

The team prints the MOULD, not the object (paper Fig. 6: the successful ovoid was
cast as two halves so the parting face is atmosphere during curing). This module
turns any grammar's signed-distance field into a set of printable negatives.

Three decisions here are not cosmetic, and each is computed rather than assumed.

1. PARTING PLANE = TRUE WIDEST CROSS-SECTION, not the equator.
   For the ovoid the egg taper moves the maximum cross-section off centre: the
   widest section of the default ShellParams sits at z = -20.1 mm, where the
   equator (z = 0) is only 95 % of that area. Parting at the equator therefore
   leaves a 1.18 mm re-entrant lip that has to scrape past the mould wall — on a
   green bio-cement body that is a spalled edge, and it is invisible in a render.
   `widest_section` locates the maximum by cross-sectional area on the voxel
   grid, so it works for any grammar without analytic special-casing. For a
   prismatic block every section is equally wide, so the tie is broken on the
   other cost: the plane is placed to MINIMISE DRAW DEPTH, because draft relief
   is proportional to draw depth (see 2).

2. DRAFT IS A DIRECTIONAL CONE SWEEP, AND THE DIRECTION IS NOT A FREE CHOICE.
   The object is the validated design; rescaling it to add draft would silently
   invalidate the wall thickness the drying and oxygen models depend on. Instead
   each mould surface is generated by sweeping the relevant field along the
   release direction at the draft angle — a min-plus/max-plus recursion over
   slices (`cone_sweep`).

   Working out which sweep each surface needs is the load-bearing step, because a
   plausible-looking choice yields a mould that is watertight, correctly sized and
   IMPOSSIBLE TO OPEN. The kinematic condition for a fixed core of radius B(z)
   inside a body whose hole is R_hole(z), when the body is withdrawn toward +z, is

       B(z) <= min over z' <= z of R_hole(z')

   and a running minimum from below is non-increasing. So an INTEGRAL core boss
   can never widen upward: the only drafted solution is a boss that NARROWS toward
   the parting plane. That is why the block's cores come out as an hourglass
   (widest at the block's outer faces, narrowest at mid-height) rather than
   carrying the single monotonic taper `grammars.block` applies for a one-piece
   bottom-draw mould — in a split mould that taper has the wrong sense in the
   lower half.

   The same condition rules out an integral boss for the vessel: the ovoid's
   internal cavity (45 mm across at the parting plane) is wider than its Ø32 bore,
   so a boss constrained by the running minimum would be a straight Ø32 column and
   would leave the cavity unformed — casting a 32 mm wall where 26 mm was
   designed. The vessel therefore needs a LOOSE CORE per half, withdrawn upward
   through the open parting face, drafted by an `erode, down` sweep.

   Where a form already has more natural draft than theta the sweep is the
   identity, so the correction is confined to the flat band around the parting
   plane: for the ovoid it costs ~0.05 mm of cavity oversize, while for the
   prismatic block, whose walls have no natural draft, it costs
   tan(theta) * draw_depth laterally everywhere — which is why the block's web
   must be pre-thickened above the standard 25 mm minimum.

3. THE JAMMING CRITERION SPLITS INTO TWO OPPOSITE RULES.
   Aggregate passages (feed, the open parting face, the plug bore) must clear
   6 x d_max or the mix bridges and starves the mould — the same Zuriguel/Vani
   criterion the object constraints use. Liquid-only drains must do the OPPOSITE:
   they have to retain aggregate while passing the spent cementation solution, so
   they are sized deliberately BELOW the certain-clog ratio (W/d < 3) and bridge
   by design. Sizing a drain at 24 mm does not make it a better drain, it makes
   it a hole the mix falls out of. `check_apertures` classifies every aperture and
   applies the right test to each.
"""
from __future__ import annotations

from dataclasses import dataclass, asdict, field as _field
import numpy as np
import trimesh
from scipy import ndimage

from .grammars import sdf

BIG = 1.0e6


# --------------------------------------------------------------------------
# Parameters
# --------------------------------------------------------------------------
@dataclass(frozen=True)
class MouldParams:
    """Mould-side parameters. Lengths in mm, angles in degrees."""

    wall: float = 20.0            # mould wall thickness around the cavity
    draft_deg: float = 1.5        # minimum draft on every mould wall
    flange: float = 25.0          # radial/lateral flange width beyond the block
    flange_t: float = 18.0        # flange thickness on each side of the parting plane
    corner_r: float = 6.0         # rounding on the mould's own outer edges

    # registration keys: truncated cones, asymmetric so the halves mate one way
    key_count: int = 3
    key_base_d: float = 18.0
    key_top_d: float = 12.0
    key_h: float = 9.0
    key_clear: float = 0.30       # socket oversize (printed-fit clearance)
    key_r_frac: float = 0.62      # key ring radius as a fraction of flange half-span
    key_angles_deg: tuple = (0.0, 130.0, 215.0)

    # clamping
    bolt_d: float = 8.5
    bolt_count: int = 4
    bolt_r_frac: float = 0.86

    # liquid-only drains (designed to bridge — see module docstring)
    drain_d: float = 6.0
    drain_count: int = 6

    # core/plug extraction handle (shell typology only)
    stem_clear: float = 1.0       # radial clearance of the stem in its pole hole
    stem_out: float = 12.0        # how far the stem protrudes past the mould face
    collar_d: float = 60.0
    collar_t: float = 8.0
    collar_bolt_d: float = 8.5
    collar_bolt_count: int = 3


# --------------------------------------------------------------------------
# Field utilities
# --------------------------------------------------------------------------
def resample_field(d: np.ndarray, origin, pitch: float, X, Y, Z) -> np.ndarray:
    """Sample a field defined on its own grid at arbitrary world points.

    Linear interpolation of a distance field is safe for boolean use: it moves the
    zero level by less than half a voxel and never changes its topology.
    """
    origin = np.asarray(origin, float)
    idx = np.stack([(X - origin[0]) / pitch, (Y - origin[1]) / pitch,
                    (Z - origin[2]) / pitch])
    return ndimage.map_coordinates(d, idx, order=1, mode="nearest")


def slice_sdf2d(occ: np.ndarray, pitch: float, axis: int = 2) -> np.ndarray:
    """In-plane signed distance of every slice (negative inside), same shape.

    The half-voxel correction is REQUIRED, not cosmetic. The raw two-sided EDT
    measures distance to the nearest voxel CENTRE of the opposite class, so a
    solid voxel touching air reads -pitch and the air voxel touching it reads
    +pitch: the field jumps by 2*pitch across one voxel and its gradient
    magnitude is 2, not 1. Any level-set offset then moves the surface only HALF
    as far as asked, and a sweep whose per-slice step is much smaller than a voxel
    lives entirely inside that doubled band — measured 0.885 deg of draft for a
    1.5 deg request. Placing the interface half a voxel from each centre restores
    |grad| = 1 and makes the requested draft angle the delivered one.
    """
    occ = np.moveaxis(occ, axis, -1)
    out = np.empty(occ.shape, float)
    h = 0.5 * pitch
    for k in range(occ.shape[-1]):
        s = occ[..., k]
        if not s.any():
            out[..., k] = BIG
            continue
        if s.all():
            out[..., k] = -BIG
            continue
        inside = ndimage.distance_transform_edt(s, sampling=pitch)
        outside = ndimage.distance_transform_edt(~s, sampling=pitch)
        out[..., k] = np.where(s, -(inside - h), outside - h)
    return np.moveaxis(out, -1, axis)


def cone_sweep(occ: np.ndarray, pitch: float, *, axis: int = 2,
               up: bool = True, mode: str = "dilate",
               draft_deg: float = 1.5) -> np.ndarray:
    """Draft a solid by a directional cone dilation or erosion. Returns a FIELD.

    The in-plane distance comes from a per-slice 2D EDT (`slice_sdf2d`), which is
    the only formulation that stays correct everywhere. Normalising a 3D distance
    field by its in-plane gradient magnitude looks equivalent and is not: on any
    symmetry axis |grad_xy| -> 0, so the interior of a body of revolution blows up
    (measured: -40 mm became -40000 mm on the axis of a sphere), the `prev - step`
    term is then never the minimum, and the recursion silently degrades to the
    identity — a mould with no draft at all that still passes a watertightness
    check. A 2D EDT per slice is exact by construction and has no such axis.

    Which of the four combinations you need follows from WHO MOVES and WHICH WAY,
    and getting it wrong produces a mould that is watertight and unopenable.

    dilate, up    cavity of a lower half: the object is withdrawn toward +axis, so
                  the cavity must WIDEN upward.
    erode,  up    core boss standing in a lower half: the boss is fixed and the
                  object lifts off it, so the boss must NARROW upward. (An integral
                  boss cannot be drafted the other way: the release condition is
                  B(z) <= min over z' <= z of R_hole(z'), and a running minimum from
                  below is flat, so widening-upward forces a zero-draft prism.)
    erode,  down  loose core withdrawn toward +axis out of the cured body: it must
                  NARROW downward so it lifts clear of its own cavity.
    dilate, down  the mirror of the first case for the upper half.

    Recursions, with step = tan(draft) * pitch:
        dilate : G[k] = min(d[k], G[k-1] - step)     (radius grows)
        erode  : G[k] = max(d[k], G[k-1] + step)     (radius shrinks)
    """
    occ = np.asarray(occ)
    occ = occ if occ.dtype == bool else (occ <= 0)

    # Erosion is the dilation of the complement: erode(S) = ~dilate(~S). Running the
    # max-plus recursion on the solid's own field instead is correct in exact
    # arithmetic but not on a raster — the receding zero level walks INTO the
    # interior, where the two-sided EDT is irregular (diagonal neighbours make the
    # inside samples land on 0.75, 2.12, 3.35 ... rather than on a uniform ladder),
    # so the delivered angle overshoots: measured 2.50 deg for a 1.50 deg request.
    # Dilation always approaches its boundary from the outside, where the field is
    # regular, and reproduces the requested angle to 4 decimal places. Routing
    # erosion through the complement inherits that accuracy.
    if mode == "erode":
        g = cone_sweep(~occ, pitch, axis=axis, up=up, mode="dilate",
                       draft_deg=draft_deg)
        return -g

    d2 = np.moveaxis(slice_sdf2d(occ, pitch, axis=axis), axis, -1)
    o = np.moveaxis(occ, axis, -1)
    # A slice with only one class present carries the +/-BIG sentinel rather than a
    # distance, so it must RESET the recursion instead of feeding it. Otherwise the
    # running extremum latches on +/-1e6 at the first uniform slice and never
    # releases: the sweep returns an empty (or full) solid, which reads as "no
    # interference" in every downstream release check. This bites hardest through
    # the complement route above, where the empty slices beyond the object's
    # extent are uniformly SOLID.
    usable = o.any(axis=(0, 1)) & ~o.all(axis=(0, 1))
    step = np.tan(np.deg2rad(max(draft_deg, 0.0))) * pitch
    G = np.empty_like(d2)
    ks = range(d2.shape[-1]) if up else range(d2.shape[-1] - 1, -1, -1)
    prev = None
    for k in ks:
        if prev is None or not usable[k]:
            G[..., k] = d2[..., k]
        else:
            G[..., k] = np.minimum(d2[..., k], prev - step)
        prev = G[..., k] if usable[k] else None
    return np.moveaxis(G, -1, axis)


def fill_slices(occ: np.ndarray, axis: int = 2) -> np.ndarray:
    """Per-slice hole fill: recovers the OUTER FORM of a hollow body.

    Deliberately not `trimesh.fill()` / 3D `binary_fill_holes`: the outer form of
    a vessel open at both poles is not a 3D-fillable set (its cavity communicates
    with the outside), so only a slice-wise fill recovers the silhouette solid.
    """
    o = np.moveaxis(occ, axis, -1)
    out = np.stack([ndimage.binary_fill_holes(o[..., k]) for k in range(o.shape[-1])],
                   axis=-1)
    return np.moveaxis(out, -1, axis)


def widest_section(occ: np.ndarray, origin, pitch: float, axis: int = 2) -> dict:
    """Locate the maximum cross-section of the (filled) form along `axis`.

    Reports the plateau extent too: for a prism every section ties, which is the
    signal that the parting plane should instead be chosen to minimise draw depth.
    """
    filled = fill_slices(occ, axis=axis)
    area = filled.sum(axis=tuple(i for i in range(3) if i != axis)) * pitch ** 2
    k = int(np.argmax(area))
    coord = float(np.asarray(origin, float)[axis] + k * pitch)
    nz = np.flatnonzero(area > 0)
    plateau = np.flatnonzero(area >= 0.999 * area[k])
    lo = float(np.asarray(origin, float)[axis] + plateau.min() * pitch)
    hi = float(np.asarray(origin, float)[axis] + plateau.max() * pitch)
    return {
        "index": k,
        "coord": coord,
        "area_mm2": float(area[k]),
        "r_equiv_mm": float(np.sqrt(area[k] / np.pi)),
        "plateau_lo": lo,
        "plateau_hi": hi,
        "plateau_width_mm": hi - lo,
        "extent_lo": float(np.asarray(origin, float)[axis] + nz.min() * pitch),
        "extent_hi": float(np.asarray(origin, float)[axis] + nz.max() * pitch),
        "area_profile": area,
        "is_prismatic": bool(hi - lo > 0.25 * (nz.max() - nz.min()) * pitch),
    }


# --------------------------------------------------------------------------
# Feature fields
# --------------------------------------------------------------------------
def frustum_field(X, Y, Z, *, r_base: float, r_top: float, z0: float, z1: float,
                  center=(0.0, 0.0)) -> np.ndarray:
    """Approximate field of a truncated cone between z0 (r_base) and z1 (r_top)."""
    t = np.clip((Z - z0) / max(z1 - z0, 1e-9), 0.0, 1.0)
    r = r_base + (r_top - r_base) * t
    rad = np.sqrt((X - center[0]) ** 2 + (Y - center[1]) ** 2)
    return np.maximum(rad - r, np.maximum(z0 - Z, Z - z1))


def ring_positions(n: int, angles_deg, radius: float) -> list[tuple[float, float]]:
    ang = list(angles_deg)[:n] if len(angles_deg) >= n else \
        [i * 360.0 / n for i in range(n)]
    return [(radius * np.cos(np.deg2rad(a)), radius * np.sin(np.deg2rad(a))) for a in ang]


def ring_positions_rect(n: int, angles_deg, half_x: float, half_y: float) -> list:
    """Same angular pattern, projected onto a RECTANGULAR perimeter.

    A circular ring is wrong for a prismatic mould and fails silently: on the
    390 x 190 block a radius sized to clear the long side puts the keys at
    y = 197 mm when the flange only reaches y = 143 mm, so every key lands in air
    and `assemble`'s intersection with the half quietly deletes it. The mould then
    prints with no registration at all while every volume check still closes,
    because a feature that was never there cannot unbalance anything. Projecting
    the same angles onto the rectangle keeps the chirality argument intact while
    guaranteeing the keys sit on material.
    """
    ang = list(angles_deg)[:n] if len(angles_deg) >= n else \
        [i * 360.0 / n for i in range(n)]
    out = []
    for a in ang:
        c, s = np.cos(np.deg2rad(a)), np.sin(np.deg2rad(a))
        t = min(half_x / abs(c) if abs(c) > 1e-9 else np.inf,
                half_y / abs(s) if abs(s) > 1e-9 else np.inf)
        out.append((t * c, t * s))
    return out


def keys_are_chiral(angles_deg, n: int) -> bool:
    """True if a key ring on a CIRCULAR flange admits one mating orientation only.

    Valid for a circular flange, whose symmetry group is the full O(2): the test
    is that the angular gap sequence is invariant under no rotation and under no
    reflection. Use `keys_are_chiral_xy` for any other flange outline — a
    rectangle's symmetry group is only {identity, 180 deg, two mirrors}, so an
    angular pattern that is chiral on a circle can become symmetric once it is
    projected onto the rectangle (measured: (0, 118, 242) deg projects onto the
    390 x 190 flange as a mirror-symmetric triple).
    """
    a = np.sort(np.mod(np.asarray(angles_deg[:n], float), 360.0))
    if len(a) < 3:
        return False
    gaps = np.diff(np.concatenate([a, a[:1] + 360.0]))
    if len(set(np.round(gaps, 3))) == 1:
        return False                      # rotationally symmetric
    for rot in np.arange(0, 360, 0.5):    # mirror + any rotation
        b = np.sort(np.mod(-a + rot, 360.0))
        if np.allclose(np.diff(np.concatenate([b, b[:1] + 360.0])), gaps, atol=1e-6):
            return False
    return True


def keys_are_chiral_xy(pts, *, rectangular: bool = True) -> tuple:
    """Chirality of an explicit key layout, tested against the flange's own group.

    The halves meet face to face, so a candidate mis-assembly is any symmetry of
    the flange outline that maps the key set onto itself. For a rectangle that is
    the 180 deg rotation and the two axis mirrors; testing those four is exact,
    where the circular gap-sequence test is not applicable.
    """
    P = np.asarray(pts, float)

    def same(A, B):
        return (sorted(map(tuple, np.round(A, 3)))
                == sorted(map(tuple, np.round(B, 3))))

    if same(P, -P):
        return False, "180-rotation symmetric"
    if not rectangular:
        return keys_are_chiral(np.degrees(np.arctan2(P[:, 1], P[:, 0])), len(P)), "circular"
    for M in ([[1, 0], [0, -1]], [[-1, 0], [0, 1]]):
        Q = P @ np.asarray(M, float).T
        if same(P, Q):
            return False, "mirror symmetric"
        if same(P, -Q):
            return False, "mirror+180 symmetric"
    return True, "chiral"


# --------------------------------------------------------------------------
# Aperture bookkeeping
# --------------------------------------------------------------------------
@dataclass
class Aperture:
    name: str
    kind: str            # "aggregate" | "liquid"
    clear_mm: float
    note: str = ""


def check_apertures(aps, d_max: float, *, jam_mult: float = 6.0,
                    certain_clog_mult: float = 3.0) -> dict:
    """Apply the correct jamming test to each aperture class.

    aggregate: clear >= jam_mult * d_max (Zuriguel 2005 Rc = 4.94 spheres /
               6.0 angular; below this the mix bridges and starves the feature)
    liquid   : clear <= certain_clog_mult * d_max (Vani 2022: always clogs below
               W/d = 3, which is exactly the retention a drain needs)
    """
    rows, ok = [], True
    for a in aps:
        ratio = a.clear_mm / d_max if d_max > 0 else np.inf
        if a.kind == "aggregate":
            passed = ratio >= jam_mult
            limit, test = jam_mult * d_max, f">= {jam_mult:g} x d_max"
        else:
            passed = ratio <= certain_clog_mult
            limit, test = certain_clog_mult * d_max, f"<= {certain_clog_mult:g} x d_max"
        ok &= passed
        rows.append({"name": a.name, "kind": a.kind, "clear_mm": a.clear_mm,
                     "ratio_over_dmax": float(ratio), "limit_mm": float(limit),
                     "test": test, "passed": bool(passed), "note": a.note})
    return {"all_passed": bool(ok), "d_max": d_max, "apertures": rows}


# --------------------------------------------------------------------------
# Verification
# --------------------------------------------------------------------------
def release_sweep(piece: np.ndarray, obj: np.ndarray, *, axis: int = 2,
                  up: bool = True, steps: int | None = None) -> dict:
    """Kinematic release test: translate `obj` along the axis and look for contact.

    A boolean-difference cavity can be watertight, correctly sized and still
    impossible to open; only a swept-interference test catches that. Returns the
    first interfering step (None if the object clears completely).
    """
    n = piece.shape[axis] if steps is None else steps
    first, worst = None, 0
    for s in range(1, n + 1):
        shifted = np.roll(obj, s if up else -s, axis=axis)
        sl = [slice(None)] * 3
        sl[axis] = slice(0, s) if up else slice(obj.shape[axis] - s, obj.shape[axis])
        shifted[tuple(sl)] = False
        hits = int((shifted & piece).sum())
        if hits > 0:
            worst = max(worst, hits)
            if first is None:
                first = s
    return {"clears": first is None, "first_interference_step": first,
            "max_interfering_voxels": worst, "steps_tested": n}


def volume_balance(box: np.ndarray, parts: dict, pitch: float) -> dict:
    """Exact partition check: the pieces plus the object must tile the mould block.

    Done on occupancy, where a partition is exact by construction, so any non-zero
    residual or overlap is a coding error rather than discretisation noise. Mesh
    volumes are reported separately because those DO carry marching-cubes error.
    """
    names = list(parts)
    union = np.zeros_like(box)
    overlap = 0
    for k in names:
        overlap += int((union & parts[k]).sum())
        union |= parts[k]
    v = pitch ** 3
    return {
        "box_mm3": float(box.sum() * v),
        "parts_mm3": {k: float(parts[k].sum() * v) for k in names},
        "sum_parts_mm3": float(sum(parts[k].sum() for k in names) * v),
        "missing_mm3": float((box & ~union).sum() * v),
        "outside_box_mm3": float((union & ~box).sum() * v),
        "overlap_mm3": float(overlap * v),
        "residual_mm3": float(((box.sum() - union.sum()) if True else 0) * v),
        "residual_frac": float(abs(box.sum() - union.sum()) / max(box.sum(), 1)),
        "exact": bool(overlap == 0 and (box & ~union).sum() == 0
                      and (union & ~box).sum() == 0),
    }


def mesh_report(m: trimesh.Trimesh) -> dict:
    return {"watertight": bool(m.is_watertight), "winding_consistent": bool(m.is_winding_consistent),
            "volume_mm3": float(m.volume), "area_mm2": float(m.area),
            "euler_number": int(m.euler_number), "bodies": int(m.body_count),
            "faces": int(len(m.faces)), "vertices": int(len(m.vertices))}


# --------------------------------------------------------------------------
# Structural sizing of the mould wall itself
# --------------------------------------------------------------------------
def wall_deflection(q_kPa: float, span_mm: float, t_mm: float, *,
                    E_GPa: float = 2.0, nu: float = 0.4) -> dict:
    """Centre deflection of a simply-supported square mould wall panel.

    Kirchhoff plate, uniform pressure: w = 0.00406 q a^4 / D, D = E t^3/(12(1-nu^2)).
    The load is the wet mix's hydrostatic head times a compaction/tamping factor;
    the deflection target is what sets the wall, because a mould that bulges casts
    an out-of-tolerance wall thickness, and wall thickness is the parameter the
    drying and oxygen models are most sensitive to.
    """
    E = E_GPa * 1e9
    D = E * (t_mm * 1e-3) ** 3 / (12 * (1 - nu ** 2))
    w = 0.00406 * (q_kPa * 1e3) * (span_mm * 1e-3) ** 4 / D
    return {"q_kPa": q_kPa, "span_mm": span_mm, "t_mm": t_mm, "D_Nm": D,
            "w_center_mm": w * 1e3}


def mix_pressure(depth_mm: float, *, rho_kg_m3: float = 1890.0,
                 compaction_factor: float = 10.0) -> dict:
    """Design pressure on the mould wall from the wet granular mix."""
    p = rho_kg_m3 * 9.81 * (depth_mm * 1e-3) / 1e3
    return {"rho_kg_m3": rho_kg_m3, "depth_mm": depth_mm, "p_static_kPa": p,
            "compaction_factor": compaction_factor,
            "p_design_kPa": p * compaction_factor}


# --------------------------------------------------------------------------
# Mould block envelopes
# --------------------------------------------------------------------------
def cup_flange_block(X, Y, Z, *, r_cup: float, z_lo: float, z_hi: float,
                     parting: float, flange: float, flange_t: float,
                     square: bool = False, half_x: float = 0.0,
                     half_y: float = 0.0) -> np.ndarray:
    """Mould-block envelope: a cup (cylinder or box) plus a parting-plane flange.

    The flange is what makes the mould clampable and is where the registration
    keys and bolts live, so it must be thick enough to house a key socket without
    breaking through to the outside face.
    """
    if square:
        cup = sdf.sd_box(X, Y, Z, half_x + 0.0, half_y + 0.0, (z_hi - z_lo) / 2,
                         center=(0.0, 0.0, (z_hi + z_lo) / 2))
        fl = sdf.sd_box(X, Y, Z, half_x + flange, half_y + flange, flange_t,
                        center=(0.0, 0.0, parting))
    else:
        cup = sdf.sd_cylinder_z(X, Y, Z, r_cup, (z_hi - z_lo) / 2,
                                center=(0.0, 0.0, (z_hi + z_lo) / 2))
        fl = sdf.sd_cylinder_z(X, Y, Z, r_cup + flange, flange_t,
                               center=(0.0, 0.0, parting))
    return np.minimum(cup, fl)


# --------------------------------------------------------------------------
# Assembly
# --------------------------------------------------------------------------
def assemble(*, obj_occ, cavity_occ, block_occ, X, Y, Z, origin, pitch,
             parting: float, mp: MouldParams, r_ref: float,
             gate_specs=(), drain_specs=(), square: bool = False,
             half_x: float = 0.0, half_y: float = 0.0,
             key_xy=None, bolt_xy=None) -> dict:
    """Cut a two-part mould out of `block_occ` and account for every void.

    Verification strategy: rather than trusting a hand-written list of the volumes
    that ought to be missing, the residual is computed as

        residual = block - lower - upper - cavity

    and then ATTRIBUTED by intersecting it with each named feature. Any void the
    named features cannot explain shows up as `unattributed_mm3`, which is the
    number that actually catches a mis-signed boolean or a feature that silently
    cut through a wall. A hand-tallied balance cannot do that, because a wrong
    boolean changes both sides of the tally at once.
    """
    origin = np.asarray(origin, float)
    v = pitch ** 3
    k_part = int(round((parting - origin[2]) / pitch))
    below = np.zeros(block_occ.shape, bool)
    below[:, :, :k_part] = True
    L0 = block_occ & below
    U0 = block_occ & ~below

    r_key = r_ref + mp.key_r_frac * mp.flange
    r_bolt = r_ref + mp.bolt_r_frac * mp.flange
    bolt_ang = [60.0 + i * 360.0 / mp.bolt_count for i in range(mp.bolt_count)]
    if key_xy is None:
        key_xy = (ring_positions_rect(mp.key_count, mp.key_angles_deg,
                                      half_x + mp.key_r_frac * mp.flange,
                                      half_y + mp.key_r_frac * mp.flange)
                  if square else
                  ring_positions(mp.key_count, mp.key_angles_deg, r_key))
    if bolt_xy is None:
        bolt_xy = (ring_positions_rect(mp.bolt_count, bolt_ang,
                                       half_x + mp.bolt_r_frac * mp.flange,
                                       half_y + mp.bolt_r_frac * mp.flange)
                   if square else
                   ring_positions(mp.bolt_count, bolt_ang, r_bolt))
    key_xy, bolt_xy = list(key_xy), list(bolt_xy)

    # registration keys: truncated cones on the lower half, sockets in the upper
    dowel = np.zeros(block_occ.shape, bool)
    socket = np.zeros(block_occ.shape, bool)
    for (kx, ky) in key_xy:
        dowel |= frustum_field(X, Y, Z, r_base=mp.key_base_d / 2,
                               r_top=mp.key_top_d / 2, z0=parting,
                               z1=parting + mp.key_h, center=(kx, ky)) <= 0
        socket |= frustum_field(X, Y, Z, r_base=mp.key_base_d / 2 + mp.key_clear,
                                r_top=mp.key_top_d / 2 + mp.key_clear, z0=parting,
                                z1=parting + mp.key_h + mp.key_clear,
                                center=(kx, ky)) <= 0
    dowel &= U0
    socket &= U0

    # clamping bolts: through both halves, in the flange
    bolts = np.zeros(block_occ.shape, bool)
    for (bx, by) in bolt_xy:
        bolts |= sdf.sd_cylinder_z(X, Y, Z, mp.bolt_d / 2, 1e4,
                                   center=(bx, by, parting)) <= 0

    # feed / vent gates: radial channels at the parting plane (aggregate class)
    gates = np.zeros(block_occ.shape, bool)
    for spec in gate_specs:
        gates |= spec(X, Y, Z) <= 0
    gates &= U0

    # liquid-only drains through the lower half (they bridge by design)
    drains = np.zeros(block_occ.shape, bool)
    for spec in drain_specs:
        drains |= spec(X, Y, Z) <= 0
    drains &= L0

    lower = (L0 & ~cavity_occ & ~drains & ~bolts) | (dowel & ~cavity_occ)
    upper = U0 & ~cavity_occ & ~gates & ~bolts & ~socket

    cav_in = cavity_occ & block_occ
    residual = block_occ & ~lower & ~upper & ~cav_in
    named = {"drains": drains, "bolts": bolts, "gates": gates,
             "key_clearance": socket & ~dowel}
    attributed = np.zeros_like(residual)
    attr = {}
    for k, feat in named.items():
        hit = residual & feat & ~attributed
        attr[k + "_mm3"] = float(hit.sum() * pitch ** 3)
        attributed |= hit
    unattributed = residual & ~attributed

    balance = {
        "block_mm3": float(block_occ.sum() * v),
        "lower_mm3": float(lower.sum() * v),
        "upper_mm3": float(upper.sum() * v),
        "cavity_in_block_mm3": float(cav_in.sum() * v),
        "residual_void_mm3": float(residual.sum() * v),
        **attr,
        "unattributed_mm3": float(unattributed.sum() * v),
        "sum_all_mm3": float((lower.sum() + upper.sum() + cav_in.sum()
                              + residual.sum()) * v),
        "overlap_lower_upper_mm3": float((lower & upper).sum() * v),
        "overlap_lower_cavity_mm3": float((lower & cav_in).sum() * v),
        "overlap_upper_cavity_mm3": float((upper & cav_in).sum() * v),
        "outside_block_mm3": float(((lower | upper) & ~block_occ).sum() * v),
    }
    balance["closure_residual_mm3"] = balance["sum_all_mm3"] - balance["block_mm3"]
    balance["closure_residual_frac"] = (balance["closure_residual_mm3"]
                                       / max(balance["block_mm3"], 1e-9))
    balance["exact"] = bool(
        abs(balance["closure_residual_mm3"]) < 1e-6
        and balance["overlap_lower_upper_mm3"] == 0.0
        and balance["overlap_lower_cavity_mm3"] == 0.0
        and balance["overlap_upper_cavity_mm3"] == 0.0
        and balance["outside_block_mm3"] == 0.0
        and balance["unattributed_mm3"] == 0.0)

    return {"lower": lower, "upper": upper, "cavity": cav_in, "dowel": dowel,
            "socket": socket, "bolts": bolts, "gates": gates, "drains": drains,
            "L0": L0, "U0": U0, "k_part": k_part, "balance": balance,
            "r_key": r_key, "r_bolt": r_bolt,
            "key_xy": key_xy, "bolt_xy": bolt_xy,
            "key_volume_mm3": float(dowel.sum() * v),
            "key_volume_nominal_mm3": float(
                mp.key_count * np.pi * mp.key_h / 3.0
                * ((mp.key_base_d / 2) ** 2 + (mp.key_base_d / 2) * (mp.key_top_d / 2)
                   + (mp.key_top_d / 2) ** 2)),
            "keys_chiral": keys_are_chiral_xy(key_xy, rectangular=square)}


def occ_to_mesh(occ: np.ndarray, origin, pitch: float, *, largest: bool = True):
    """Mesh an occupancy set, keeping the largest body and repairing normals."""
    d = sdf.signed_distance_from_binary(occ, pitch)
    m = sdf.mesh_field(d, np.asarray(origin, float), pitch)
    if largest and m.body_count > 1:
        m = max(m.split(only_watertight=False), key=lambda x: x.volume)
    m.fill_holes()
    trimesh.repair.fix_normals(m)
    return m


# --------------------------------------------------------------------------
# High-level drivers
# --------------------------------------------------------------------------
def build_shell_mould(p, mp: MouldParams | None = None, pitch: float = 1.25) -> dict:
    """Two-part mould plus two loose cores for a hollow ovoid vessel.

    The parting plane is placed on the COMPUTED widest section, not the equator.
    Cores are loose because an integral boss cannot clear the vessel's cavity
    (see the module docstring); each is withdrawn from its own half, which is
    consistent with the split-mould workflow where the halves cure separately.
    """
    from .grammars import shell
    mp = mp or MouldParams(wall=20.0, draft_deg=2.5, flange=25.0, flange_t=18.0,
                           key_r_frac=0.35, bolt_r_frac=0.78)

    obj_m, d_obj, o_obj, _ = shell.build(p, pitch=pitch, return_field=True)
    occ0 = d_obj <= 0.0
    form0 = fill_slices(occ0, axis=2)
    ws = widest_section(occ0, o_obj, pitch, axis=2)
    parting, r_max = ws["coord"], ws["r_equiv_mm"]
    r_cup = r_max + mp.wall
    z_lo = obj_m.bounds[0][2] - mp.wall
    z_hi = obj_m.bounds[1][2] + mp.wall

    pad = mp.flange + 3 * pitch
    X, Y, Z, origin, sh = sdf.make_grid(
        [-(r_cup + pad), -(r_cup + pad), z_lo - 2 * pitch],
        [r_cup + pad, r_cup + pad, z_hi + 2 * pitch], pitch)
    form = resample_field(sdf.signed_distance_from_binary(form0, pitch),
                          o_obj, pitch, X, Y, Z) <= 0.0
    obj = resample_field(d_obj, o_obj, pitch, X, Y, Z) <= 0.0
    block = cup_flange_block(X, Y, Z, r_cup=r_cup, z_lo=z_lo, z_hi=z_hi,
                             parting=parting, flange=mp.flange,
                             flange_t=mp.flange_t) <= 0.0

    k_part = int(round((parting - origin[2]) / pitch))
    below = np.zeros(sh, bool)
    below[:, :, :k_part] = True
    cav_lo = cone_sweep(form & below, pitch, up=True, mode="dilate",
                        draft_deg=mp.draft_deg) <= 0
    cav_up = cone_sweep(form & ~below, pitch, up=False, mode="dilate",
                        draft_deg=mp.draft_deg) <= 0
    cavity = (cav_lo & below) | (cav_up & ~below)

    gate_d = 26.0
    def _gate(ang):
        ca, sa = np.cos(np.deg2rad(ang)), np.sin(np.deg2rad(ang))
        def f(X, Y, Z):
            u = X * ca + Y * sa
            w = -X * sa + Y * ca
            return np.maximum.reduce([
                np.sqrt(w ** 2 + (Z - parting) ** 2) - gate_d / 2,
                -u, u - (r_cup + mp.flange)])
        return f
    r_drain = 25.0
    def _drain(ang):
        dx = r_drain * np.cos(np.deg2rad(ang))
        dy = r_drain * np.sin(np.deg2rad(ang))
        return lambda X, Y, Z: sdf.sd_cylinder_z(X, Y, Z, mp.drain_d / 2, 1e4,
                                                 center=(dx, dy, 0.0))
    A = assemble(obj_occ=obj, cavity_occ=cavity, block_occ=block, X=X, Y=Y, Z=Z,
                 origin=origin, pitch=pitch, parting=parting, mp=mp, r_ref=r_cup,
                 gate_specs=[_gate(30.0), _gate(210.0)],
                 drain_specs=[_drain(15.0 + i * 360.0 / mp.drain_count)
                              for i in range(mp.drain_count)], square=False)

    hollow = form & ~obj
    core_lo = (cone_sweep(hollow & below, pitch, up=False, mode="erode",
                          draft_deg=mp.draft_deg) <= 0) & below
    core_up = (cone_sweep(hollow & ~below, pitch, up=True, mode="erode",
                          draft_deg=mp.draft_deg) <= 0) & ~below
    A.update(obj=obj, form=form, block=block, cavity_full=cavity, hollow=hollow,
             core_lo=core_lo, core_up=core_up, below=below, origin=origin,
             pitch=pitch, parting=parting, widest=ws, r_cup=r_cup,
             gate_d=gate_d, r_drain=r_drain, mp=mp, obj_mesh=obj_m)
    return A


def build_block_mould(p, mp: MouldParams | None = None, pitch: float = 2.0) -> dict:
    """Two-part mould for a hollow-core masonry unit, parted across the core axis.

    Every section of a prism ties for width, so the parting plane is chosen on the
    other cost — minimum draw depth (H/2 rather than H). Draft is taken by ERODING
    away from the parting plane, so the nominal section is preserved at the parting
    plane and the relief lands on the outer faces, inside ASTM C90's +/-3.2 mm
    dimensional tolerance. That same erosion is what turns the cores into the
    hourglass bosses a split mould requires.
    """
    from .grammars import block
    mp = mp or MouldParams(wall=20.0, draft_deg=1.5, flange=28.0, flange_t=20.0,
                           key_base_d=22.0, key_top_d=15.0, key_h=11.0,
                           key_angles_deg=(30.0, 150.0, 275.0), bolt_d=10.5,
                           bolt_count=6, bolt_r_frac=0.72, key_r_frac=0.30,
                           drain_count=8)
    obj_m, d_obj, o_obj, _ = block.build(p, pitch=pitch, return_field=True)
    hx, hy = p.L / 2 + mp.wall, p.W / 2 + mp.wall
    z_lo, z_hi = -p.H / 2 - mp.wall, p.H / 2 + mp.wall
    parting = 0.0

    pad = mp.flange + 3 * pitch
    X, Y, Z, origin, sh = sdf.make_grid([-(hx + pad), -(hy + pad), z_lo - 2 * pitch],
                                        [hx + pad, hy + pad, z_hi + 2 * pitch], pitch)
    obj = resample_field(d_obj, o_obj, pitch, X, Y, Z) <= 0.0
    block_occ = cup_flange_block(X, Y, Z, r_cup=0.0, z_lo=z_lo, z_hi=z_hi,
                                 parting=parting, flange=mp.flange,
                                 flange_t=mp.flange_t, square=True,
                                 half_x=hx, half_y=hy) <= 0.0
    k_part = int(round((parting - origin[2]) / pitch))
    below = np.zeros(sh, bool)
    below[:, :, :k_part] = True
    cav_lo = cone_sweep(obj & below, pitch, up=False, mode="erode",
                        draft_deg=mp.draft_deg) <= 0
    cav_up = cone_sweep(obj & ~below, pitch, up=True, mode="erode",
                        draft_deg=mp.draft_deg) <= 0
    cavity = (cav_lo & below) | (cav_up & ~below)

    gate_w = 26.0
    def _gate(sgn_y, xc):
        def f(X, Y, Z):
            return np.maximum.reduce([
                np.abs(X - xc) - gate_w / 2, np.abs(Z - parting) - gate_w / 2,
                sgn_y * Y - (hy + mp.flange), -(sgn_y * Y - (p.W / 2 - 6 * pitch))])
        return f
    def _drain(dx, dy):
        return lambda X, Y, Z: sdf.sd_cylinder_z(X, Y, Z, mp.drain_d / 2, 1e4,
                                                 center=(dx, dy, 0.0))
    A = assemble(obj_occ=obj, cavity_occ=cavity, block_occ=block_occ, X=X, Y=Y, Z=Z,
                 origin=origin, pitch=pitch, parting=parting, mp=mp, r_ref=hx,
                 gate_specs=[_gate(s, x) for s in (+1, -1) for x in (-110.0, 110.0)],
                 drain_specs=[_drain(dx, dy) for dx in (-150., -50., 50., 150.)
                              for dy in (-55., 55.)],
                 square=True, half_x=hx, half_y=hy)
    A.update(obj=obj, block=block_occ, cavity_full=cavity, below=below,
             origin=origin, pitch=pitch, parting=parting, mp=mp, obj_mesh=obj_m,
             gate_w=gate_w, draw_depth=p.H / 2,
             relief_per_face=float(np.tan(np.deg2rad(mp.draft_deg)) * p.H / 2))
    return A
